spring:
  application:
    name: bankbot-chats
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/bankbot-db}
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS} | %-20.20thread | %highlight(%-5level) | %magenta(%-25.25logger{25}) | %m%n"